#!/usr/bin/env bash
# Builds termoweb-local-schedule-card.es5.js from the six frontend source
# files, for browsers that Home Assistant's own isModern check routes to the
# es5=True extra js list (a classic <script src> tag, not an ES module
# import). Run this after editing any source file and commit the result;
# tests/test_frontend_bundle.py fails loudly if the committed bundle goes
# stale.
set -euo pipefail

ESBUILD_VERSION="0.28.2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENTRY="termoweb-local-schedule-card.js"
OUTFILE="termoweb-local-schedule-card.es5.js"

# Sorted alphabetically by filename; must match the order
# tests/test_frontend_bundle.py hashes.
SOURCES=(
  "presets.js"
  "schedule-card-editor.js"
  "schedule-card.js"
  "schedule-grid.js"
  "schedule-styles.js"
  "termoweb-local-schedule-card.js"
)

TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_OUT"' EXIT

npx --yes "esbuild@${ESBUILD_VERSION}" "$ENTRY" \
  --bundle \
  --format=iife \
  --target=es2017 \
  --outfile="$TMP_OUT"

SOURCES_SHA256="$(cat "${SOURCES[@]}" | sha256sum | cut -d' ' -f1)"

{
  printf '/* sources-sha256: %s */\n' "$SOURCES_SHA256"
  printf '/* generated by frontend/build-es5.sh, do not hand-edit. */\n'
  cat "$TMP_OUT"
} > "$OUTFILE"

echo "sources-sha256: $SOURCES_SHA256"
echo "wrote $SCRIPT_DIR/$OUTFILE"
