/* sources-sha256: dea1e087b46f3601bd6dfdea66afdc12a83bfe7d0b536bad282b536a22eaefbd */
/* generated by frontend/build-es5.sh, do not hand-edit. */
(() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };

  // schedule-card-editor.js
  var SCHEMA = [
    {
      name: "entity",
      required: true,
      selector: { entity: { domain: "climate", integration: "termoweb_local" } }
    },
    { name: "title", selector: { text: {} } }
  ];
  var LABELS = { entity: "Heater", title: "Title" };
  function computeLabel(schema) {
    return LABELS[schema.name] || schema.name;
  }
  var TermowebLocalScheduleCardEditor = class extends HTMLElement {
    setConfig(config) {
      this._config = config || {};
      this._render();
    }
    set hass(hass) {
      this._hass = hass;
      this._render();
    }
    get hass() {
      return this._hass;
    }
    connectedCallback() {
      this._render();
    }
    _render() {
      if (!this._hass) return;
      if (!this._form) {
        this._form = document.createElement("ha-form");
        this._form.addEventListener("value-changed", (ev) => {
          ev.stopPropagation();
          const config = __spreadValues(__spreadValues({}, this._config), ev.detail.value);
          this._config = config;
          this.dispatchEvent(
            new CustomEvent("config-changed", { detail: { config }, bubbles: true, composed: true })
          );
        });
        this.innerHTML = "";
        this.appendChild(this._form);
      }
      this._form.hass = this._hass;
      this._form.schema = SCHEMA;
      this._form.data = this._config;
      this._form.computeLabel = computeLabel;
    }
  };
  if (!customElements.get("termoweb-local-schedule-card-editor")) {
    customElements.define("termoweb-local-schedule-card-editor", TermowebLocalScheduleCardEditor);
  }

  // presets.js
  var PRESETS = [
    { code: 0, key: "cold", label: "Cold", color: "#3d7dc4" },
    { code: 1, key: "night", label: "Night", color: "#7c5cbf" },
    { code: 2, key: "day", label: "Day", color: "#e08a1e" }
  ];
  var PRESET_BY_CODE = new Map(PRESETS.map((p) => [p.code, p]));
  var UNSET_COLOR = "var(--disabled-text-color, #9e9e9e)";
  var PRESET_STEP_C = 0.5;
  var MIN_PRESET_C = 7;
  var MAX_PRESET_C = 35;
  function presetBounds(code, ptemp) {
    const antifrost = ptemp ? ptemp[0] : null;
    const eco = ptemp ? ptemp[1] : null;
    const comfort = ptemp ? ptemp[2] : null;
    if (code === 0) {
      return { min: MIN_PRESET_C, max: (eco != null ? eco : MAX_PRESET_C) - PRESET_STEP_C };
    }
    if (code === 1) {
      return {
        min: (antifrost != null ? antifrost : MIN_PRESET_C) + PRESET_STEP_C,
        max: (comfort != null ? comfort : MAX_PRESET_C) - PRESET_STEP_C
      };
    }
    if (code === 2) {
      return { min: (eco != null ? eco : MIN_PRESET_C) + PRESET_STEP_C, max: MAX_PRESET_C };
    }
    return { min: MIN_PRESET_C, max: MAX_PRESET_C };
  }

  // schedule-styles.js
  var SCHEDULE_CARD_STYLES = `
  [hidden] { display: none !important; }
  :host { display: block; }
  ha-card { padding: 16px; box-sizing: border-box; font-size: calc(1em - 1px); }
  .header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 12px; }
  .title { font-size: 1.1em; font-weight: 500; color: var(--primary-text-color); }
  .note { font-size: 0.85em; color: var(--secondary-text-color); margin-top: 4px; }
  .error { font-size: 0.85em; color: var(--error-color, #db4437); margin-top: 8px; }
  .legend { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 4px; }
  .swatch { display: flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 16px;
    cursor: pointer; background: var(--secondary-background-color, rgba(127,127,127,0.1)); }
  .swatch .dot { width: 14px; height: 14px; border-radius: 50%; flex: none; }
  .swatch .label { font-size: 0.9em; color: var(--primary-text-color); }
  .legend-caption { margin-top: 0; margin-bottom: 12px; }
  .swatch-view { align-items: center; gap: 6px; }
  .swatch:not(.editing) .swatch-view { display: flex; }
  .swatch.editing .swatch-view { display: none; }
  .swatch-stepper { align-items: center; gap: 4px; }
  .swatch.editing .swatch-stepper { display: flex; }
  .swatch:not(.editing) .swatch-stepper { display: none; }
  .preset-editor-value { font-size: 0.9em; color: var(--primary-text-color); min-width: 3.5em; text-align: center; }
  .preset-step, .preset-confirm, .preset-cancel { font-size: 0.9em; width: 24px; height: 24px;
    border-radius: 50%; border: none; cursor: pointer;
    background: var(--secondary-background-color, rgba(127,127,127,0.2)); color: var(--primary-text-color); }
  .preset-confirm { color: var(--success-color, #2e7d32); }
  .preset-cancel { color: var(--error-color, #db4437); }
  .preset-step:disabled, .preset-confirm:disabled, .preset-cancel:disabled { opacity: 0.5; cursor: default; }
  .preset-editor-error { margin-top: 0; margin-bottom: 12px; }
  .grid-scroll { overflow-x: auto; }
  .grid { display: table; border-collapse: separate; border-spacing: 2px; }
  .grid-row { display: table-row; }
  .row-label { display: table-cell; vertical-align: middle; padding-right: 8px;
    font-size: 0.85em; color: var(--secondary-text-color); white-space: nowrap; position: sticky; left: 0;
    background: var(--card-background-color); }
  .cell { display: table-cell; width: 14px; height: 22px; min-width: 14px; cursor: pointer;
    border-radius: 2px; border: 1px solid var(--divider-color); touch-action: none; pointer-events: auto; }
  .cell.unset { background-image: repeating-linear-gradient(45deg, transparent, transparent 3px, rgba(0,0,0,0.15) 3px, rgba(0,0,0,0.15) 6px); }
  .cell:focus { outline: 2px solid var(--primary-color); outline-offset: -2px; }
  .row-actions { display: table-cell; padding-left: 8px; vertical-align: middle; }
  .copy-row-btn { font-size: 0.75em; color: var(--primary-color); background: none; border: none; cursor: pointer; padding: 2px 4px; }
  .copy-confirm, .copy-cancel { font-size: 0.9em; width: 22px; height: 22px; border-radius: 50%; border: none; cursor: pointer;
    background: var(--secondary-background-color, rgba(127,127,127,0.2)); }
  .copy-confirm { color: var(--success-color, #2e7d32); }
  .copy-cancel { color: var(--error-color, #db4437); margin-left: 2px; }
  .copy-target-checkbox { cursor: pointer; width: 16px; height: 16px; }
  .hour-labels { display: table-row; }
  .hour-label-spacer { display: table-cell; }
  .hour-label { display: table-cell; font-size: 0.7em; color: var(--secondary-text-color); text-align: left; }
  .actions { display: flex; gap: 8px; margin-top: 14px; align-items: center; }
  button.action { font-size: 0.9em; padding: 6px 14px; border-radius: 4px; border: none; cursor: pointer;
    background: var(--primary-color); color: var(--text-primary-color, #fff); }
  button.action.secondary { background: var(--secondary-background-color, rgba(127,127,127,0.2)); color: var(--primary-text-color); }
  button.action:disabled { opacity: 0.5; cursor: default; }
  .dirty-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--primary-color); display: inline-block; margin-left: 6px; }
  .copy-all-btn { font-size: 0.8em; color: var(--primary-color); background: none; border: 1px solid var(--divider-color);
    border-radius: 4px; cursor: pointer; padding: 4px 8px; }
`;

  // schedule-grid.js
  var DAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  var DAYS_PER_WEEK = 7;
  var HALF_HOURLY_LENGTH = 336;
  function slotsPerDayFor(length) {
    return length === HALF_HOURLY_LENGTH ? 48 : 24;
  }
  function hoursPerSlotFor(slotsPerDay) {
    return 24 / slotsPerDay;
  }
  function arraysEqual(a, b) {
    if (a === b) return true;
    if (!a || !b || a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      if (a[i] !== b[i]) return false;
    }
    return true;
  }
  function formatTemp(value) {
    if (value === null || value === void 0) return null;
    const num = Number(value);
    if (Number.isNaN(num)) return null;
    return `${num.toFixed(1)}\xB0C`;
  }
  function nextPresetValue(value) {
    if (value === 0) return 1;
    if (value === 1) return 2;
    if (value === 2) return 0;
    return 0;
  }
  function formatHourLabel(hour) {
    const h = Math.floor(hour);
    const m = Math.round((hour - h) * 60);
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
  }
  function copyDayToDays(grid, sourceDay, targetDays, slotsPerDay) {
    const next = grid.slice();
    const start = sourceDay * slotsPerDay;
    const rowValues = grid.slice(start, start + slotsPerDay);
    for (const day of targetDays) {
      if (day === sourceDay) continue;
      const dest = day * slotsPerDay;
      for (let col = 0; col < slotsPerDay; col++) {
        next[dest + col] = rowValues[col];
      }
    }
    return next;
  }

  // schedule-card.js
  var STALE_NOTE_TEXT = "The heater's schedule changed underneath your unsaved edits. Revert to load the latest, or Save to overwrite it.";
  function isClimateEntityId(id) {
    return typeof id === "string" && id.startsWith("climate.");
  }
  var TermowebLocalScheduleCard = class extends HTMLElement {
    // HA custom-card contract: entities/entitiesFallback are entity id lists
    // the dashboard editor already knows about; hass.states is the fallback
    // when neither is populated yet (developers.home-assistant.io/docs/
    // frontend/custom-ui/custom-card#custom-card-preview-and-config).
    static getStubConfig(hass, entities, entitiesFallback) {
      const pool = Array.isArray(entities) && entities.length && entities || Array.isArray(entitiesFallback) && entitiesFallback.length && entitiesFallback || (hass && hass.states ? Object.keys(hass.states) : []);
      const marked = pool.find((id) => {
        if (!isClimateEntityId(id) || !hass || !hass.states || !hass.states[id]) return false;
        const attrs = hass.states[id].attributes || {};
        return attrs.dev_id !== void 0 && Array.isArray(attrs.prog);
      });
      if (marked) return { entity: marked };
      const anyClimate = pool.find(isClimateEntityId);
      if (anyClimate) return { entity: anyClimate };
      return { entity: "" };
    }
    static getConfigElement() {
      return document.createElement("termoweb-local-schedule-card-editor");
    }
    setConfig(config) {
      if (config && config.entity && !isClimateEntityId(config.entity)) {
        throw new Error("termoweb-local-schedule-card: 'entity' must be a climate entity");
      }
      this._config = config || {};
      this._grid = null;
      this._domGrid = null;
      this._baselineProg = null;
      this._dirty = false;
      this._saving = false;
      this._error = null;
      this._staleNote = false;
      this._ptemp = null;
      this._legendPtemp = null;
      this._editingPreset = null;
      this._presetEditValue = null;
      this._presetSaving = false;
      this._presetError = null;
      this._copySourceDay = null;
      this._copyTargets = /* @__PURE__ */ new Set();
      this._entityMissing = false;
      this._renderedSlotsPerDay = null;
      if (this._hass) {
        this._syncFromHass();
      }
      this._render();
    }
    getCardSize() {
      return 6;
    }
    set hass(hass) {
      this._hass = hass;
      this._syncFromHass();
      this._render();
    }
    get hass() {
      return this._hass;
    }
    connectedCallback() {
      if (!this.shadowRoot) {
        this.attachShadow({ mode: "open" });
      }
      this._buildSkeleton();
      if (!this._docPointerUpBound) {
        this._docPointerUpBound = true;
        const stopPaint = () => this._stopPainting();
        document.addEventListener("pointerup", stopPaint);
        document.addEventListener("pointercancel", stopPaint);
      }
      this._render();
    }
    _syncFromHass() {
      if (!this._config || !this._config.entity || !this._hass) return;
      const state = this._hass.states[this._config.entity];
      if (!state) {
        this._entityMissing = true;
        return;
      }
      this._entityMissing = false;
      const liveProg = Array.isArray(state.attributes.prog) ? state.attributes.prog.slice() : null;
      const ptemp = Array.isArray(state.attributes.ptemp) ? state.attributes.ptemp.slice() : null;
      this._ptemp = ptemp;
      this._liveProg = liveProg;
      if (this._grid === null) {
        this._resetGridFromLive();
        return;
      }
      if (!this._dirty) {
        if (!arraysEqual(liveProg, this._baselineProg)) {
          this._resetGridFromLive();
        }
        this._staleNote = false;
        return;
      }
      this._staleNote = !!(liveProg && this._baselineProg && !arraysEqual(liveProg, this._baselineProg));
    }
    _resetGridFromLive() {
      this._baselineProg = this._liveProg ? this._liveProg.slice() : null;
      this._grid = this._liveProg ? this._liveProg.slice() : null;
      this._dirty = false;
      this._staleNote = false;
    }
    _buildSkeleton() {
      const style = document.createElement("style");
      style.textContent = SCHEDULE_CARD_STYLES;
      const card = document.createElement("ha-card");
      const content = document.createElement("div");
      content.className = "content";
      card.appendChild(content);
      this.shadowRoot.innerHTML = "";
      this.shadowRoot.appendChild(style);
      this.shadowRoot.appendChild(card);
      this._content = content;
      this._renderedSlotsPerDay = null;
    }
    _render() {
      if (!this._content) return;
      const entity = this._config && this._config.entity;
      if (!entity) {
        this._renderPlaceholder("Select a heater to see its schedule.");
        return;
      }
      if (!this._hass) {
        this._renderPlaceholder("Waiting for Home Assistant...");
        return;
      }
      if (this._entityMissing) {
        this._renderPlaceholder(`Entity ${entity} not found.`, "error");
        return;
      }
      if (!this._grid) {
        this._renderPlaceholder("Waiting for schedule data...");
        return;
      }
      const slotsPerDay = slotsPerDayFor(this._grid.length);
      if (this._renderedSlotsPerDay !== slotsPerDay) {
        this._renderStructural(slotsPerDay);
      } else {
        this._patchInPlace();
      }
    }
    // Used for the non-grid states (no entity, no hass yet, missing entity,
    // no schedule data). None of these have a grid-scroll to lose scroll
    // position on, so a plain innerHTML swap is fine here.
    _renderPlaceholder(text, kind = "note") {
      this._content.innerHTML = `<div class="${kind}">${text}</div>`;
      this._renderedSlotsPerDay = null;
      this._gridEl = null;
    }
    _renderStructural(slotsPerDay) {
      const hoursPerSlot = hoursPerSlotFor(slotsPerDay);
      const title = this._config.title || "Weekly schedule";
      const prevScroll = this._content.querySelector(".grid-scroll");
      const savedScrollLeft = prevScroll ? prevScroll.scrollLeft : 0;
      this._content.innerHTML = "";
      const header = document.createElement("div");
      header.className = "header";
      const titleEl = document.createElement("div");
      titleEl.className = "title";
      titleEl.textContent = title;
      header.appendChild(titleEl);
      this._content.appendChild(header);
      this._titleEl = titleEl;
      const staleNoteEl = document.createElement("div");
      staleNoteEl.className = "note stale-note";
      staleNoteEl.hidden = true;
      this._content.appendChild(staleNoteEl);
      this._staleNoteEl = staleNoteEl;
      const legend = document.createElement("div");
      legend.className = "legend";
      legend.setAttribute("role", "group");
      legend.setAttribute("aria-label", "Preset temperatures");
      this._legendLabelEls = {};
      this._presetEls = {};
      PRESETS.forEach((preset) => {
        const swatch = document.createElement("div");
        swatch.className = "swatch";
        swatch.dataset.preset = String(preset.code);
        swatch.setAttribute("role", "button");
        swatch.tabIndex = 0;
        swatch.setAttribute("aria-label", `Edit ${preset.label} temperature`);
        const dot = document.createElement("span");
        dot.className = "dot";
        dot.style.backgroundColor = preset.color;
        swatch.appendChild(dot);
        const view = document.createElement("span");
        view.className = "swatch-view";
        const label = document.createElement("span");
        label.className = "label";
        label.textContent = this._legendLabelText(preset);
        view.appendChild(label);
        swatch.appendChild(view);
        const stepper = document.createElement("span");
        stepper.className = "swatch-stepper";
        stepper.hidden = true;
        const minusBtn = document.createElement("button");
        minusBtn.type = "button";
        minusBtn.className = "preset-step";
        minusBtn.textContent = "\u2212";
        minusBtn.setAttribute("aria-label", `Decrease ${preset.label} by ${PRESET_STEP_C}`);
        minusBtn.addEventListener("click", (ev) => {
          ev.stopPropagation();
          this._stepPreset(-PRESET_STEP_C);
        });
        stepper.appendChild(minusBtn);
        const valueEl = document.createElement("span");
        valueEl.className = "preset-editor-value";
        stepper.appendChild(valueEl);
        const plusBtn = document.createElement("button");
        plusBtn.type = "button";
        plusBtn.className = "preset-step";
        plusBtn.textContent = "+";
        plusBtn.setAttribute("aria-label", `Increase ${preset.label} by ${PRESET_STEP_C}`);
        plusBtn.addEventListener("click", (ev) => {
          ev.stopPropagation();
          this._stepPreset(PRESET_STEP_C);
        });
        stepper.appendChild(plusBtn);
        const confirmBtn = document.createElement("button");
        confirmBtn.type = "button";
        confirmBtn.className = "preset-confirm";
        confirmBtn.textContent = "\u2713";
        confirmBtn.setAttribute("aria-label", "confirm");
        confirmBtn.addEventListener("click", (ev) => {
          ev.stopPropagation();
          this._savePreset();
        });
        stepper.appendChild(confirmBtn);
        const cancelBtn = document.createElement("button");
        cancelBtn.type = "button";
        cancelBtn.className = "preset-cancel";
        cancelBtn.textContent = "\u2717";
        cancelBtn.setAttribute("aria-label", "cancel");
        cancelBtn.addEventListener("click", (ev) => {
          ev.stopPropagation();
          this._closePresetEditor();
        });
        stepper.appendChild(cancelBtn);
        swatch.appendChild(stepper);
        swatch.addEventListener("click", () => this._openPresetEditor(preset.code));
        swatch.addEventListener("keydown", (ev) => this._onSwatchKeyDown(ev, preset.code));
        legend.appendChild(swatch);
        this._legendLabelEls[preset.code] = label;
        this._presetEls[preset.code] = {
          swatch,
          dot,
          view,
          stepper,
          minusBtn,
          valueEl,
          plusBtn,
          confirmBtn,
          cancelBtn
        };
      });
      this._content.appendChild(legend);
      const caption = document.createElement("div");
      caption.className = "note legend-caption";
      caption.textContent = "Click a preset to edit its temperature.";
      this._content.appendChild(caption);
      const presetError = document.createElement("div");
      presetError.className = "error preset-editor-error";
      presetError.hidden = true;
      this._content.appendChild(presetError);
      this._presetErrorEl = presetError;
      const scroll = document.createElement("div");
      scroll.className = "grid-scroll";
      const grid = document.createElement("div");
      grid.className = "grid";
      grid.setAttribute("role", "grid");
      const hourRow = document.createElement("div");
      hourRow.className = "hour-labels";
      const spacer = document.createElement("div");
      spacer.className = "hour-label-spacer";
      hourRow.appendChild(spacer);
      const labelStep = slotsPerDay > 24 ? 6 : 2;
      for (let col = 0; col < slotsPerDay; col++) {
        const cell = document.createElement("div");
        cell.className = "hour-label";
        if (col % labelStep === 0) {
          cell.textContent = String(Math.floor(col * hoursPerSlot));
        }
        hourRow.appendChild(cell);
      }
      const spacer2 = document.createElement("div");
      spacer2.className = "hour-label-spacer";
      hourRow.appendChild(spacer2);
      grid.appendChild(hourRow);
      this._rowEls = {};
      for (let day = 0; day < DAYS_PER_WEEK; day++) {
        const row = document.createElement("div");
        row.className = "grid-row";
        row.setAttribute("role", "row");
        const label = document.createElement("div");
        label.className = "row-label";
        label.textContent = DAY_LABELS[day];
        row.appendChild(label);
        for (let col = 0; col < slotsPerDay; col++) {
          const idx = day * slotsPerDay + col;
          const cell = document.createElement("div");
          cell.dataset.idx = String(idx);
          cell.dataset.day = String(day);
          cell.dataset.slot = String(col);
          cell.setAttribute("role", "gridcell");
          cell.tabIndex = 0;
          this._applyCellVisual(cell, this._grid[idx], hoursPerSlot);
          row.appendChild(cell);
        }
        const actions = document.createElement("div");
        actions.className = "row-actions";
        const copyBtn = document.createElement("button");
        copyBtn.type = "button";
        copyBtn.className = "copy-row-btn";
        copyBtn.textContent = "Copy to";
        copyBtn.addEventListener("click", () => this._startCopyMode(day));
        actions.appendChild(copyBtn);
        const confirmBtn = document.createElement("button");
        confirmBtn.type = "button";
        confirmBtn.className = "copy-confirm";
        confirmBtn.textContent = "\u2713";
        confirmBtn.setAttribute("aria-label", "confirm copy");
        confirmBtn.hidden = true;
        confirmBtn.addEventListener("click", () => this._confirmCopy(slotsPerDay));
        actions.appendChild(confirmBtn);
        const cancelBtn = document.createElement("button");
        cancelBtn.type = "button";
        cancelBtn.className = "copy-cancel";
        cancelBtn.textContent = "\u2717";
        cancelBtn.setAttribute("aria-label", "cancel copy");
        cancelBtn.hidden = true;
        cancelBtn.addEventListener("click", () => this._cancelCopyMode());
        actions.appendChild(cancelBtn);
        const checkbox = document.createElement("input");
        checkbox.type = "checkbox";
        checkbox.className = "copy-target-checkbox";
        checkbox.setAttribute("aria-label", `copy to ${DAY_LABELS[day]}`);
        checkbox.hidden = true;
        checkbox.addEventListener("change", () => this._toggleCopyTarget(day, checkbox.checked));
        actions.appendChild(checkbox);
        row.appendChild(actions);
        this._rowEls[day] = { actions, copyBtn, confirmBtn, cancelBtn, checkbox };
        grid.appendChild(row);
      }
      grid.addEventListener("pointerdown", (ev) => this._onCellPointerDown(ev, hoursPerSlot));
      grid.addEventListener("pointermove", (ev) => this._onCellPointerMove(ev, hoursPerSlot));
      grid.addEventListener("pointerup", () => this._stopPainting());
      grid.addEventListener("pointercancel", () => this._stopPainting());
      grid.addEventListener("keydown", (ev) => this._onCellKeyDown(ev, hoursPerSlot));
      scroll.appendChild(grid);
      this._content.appendChild(scroll);
      scroll.scrollLeft = savedScrollLeft;
      const errorEl = document.createElement("div");
      errorEl.className = "error save-error";
      errorEl.hidden = true;
      this._content.appendChild(errorEl);
      this._errorEl = errorEl;
      const actionsRow = document.createElement("div");
      actionsRow.className = "actions";
      const saveBtn = document.createElement("button");
      saveBtn.className = "action";
      saveBtn.addEventListener("click", () => this._save());
      actionsRow.appendChild(saveBtn);
      this._saveBtnEl = saveBtn;
      const revertBtn = document.createElement("button");
      revertBtn.className = "action secondary";
      revertBtn.textContent = "Revert";
      revertBtn.addEventListener("click", () => {
        this._resetGridFromLive();
        this._error = null;
        this._syncCellsFromGrid(hoursPerSlot);
        this._patchLegend();
        this._patchStaleNote();
        this._patchError();
        this._updateActionsState();
        this._updateDirtyDot();
      });
      actionsRow.appendChild(revertBtn);
      this._revertBtnEl = revertBtn;
      this._content.appendChild(actionsRow);
      this._gridEl = grid;
      this._renderedSlotsPerDay = slotsPerDay;
      this._domGrid = this._grid.slice();
      this._legendPtemp = this._ptemp ? this._ptemp.slice() : null;
      this._patchStaleNote();
      this._patchError();
      this._updateSaveButtonLabel();
      this._updateActionsState();
      this._updateDirtyDot();
      this._patchPresetStepper();
      this._patchCopyMode();
    }
    // Enter/Escape while the clicked swatch is the one being edited confirm
    // or cancel it, matching the confirm/cancel buttons inside its stepper;
    // otherwise Enter/Space open the editor, same as clicking it. Returning
    // after the editing branch (rather than falling through) stops a stray
    // Space on the swatch background from reseeding an in-progress edit.
    _onSwatchKeyDown(ev, code) {
      if (this._editingPreset === code) {
        if (ev.key === "Enter") {
          ev.preventDefault();
          this._savePreset();
        } else if (ev.key === "Escape") {
          ev.preventDefault();
          this._closePresetEditor();
        }
        return;
      }
      if (ev.key !== "Enter" && ev.key !== " " && ev.key !== "Spacebar") return;
      ev.preventDefault();
      this._openPresetEditor(code);
    }
    _openPresetEditor(code) {
      if (!this._ptemp) return;
      if (this._copySourceDay !== null) this._cancelCopyMode();
      this._editingPreset = code;
      this._presetEditValue = this._ptemp[code];
      this._presetError = null;
      this._patchPresetStepper();
    }
    _closePresetEditor() {
      if (this._presetSaving) return;
      this._editingPreset = null;
      this._presetEditValue = null;
      this._presetError = null;
      this._patchPresetStepper();
    }
    _stepPreset(delta) {
      if (this._editingPreset === null || this._presetSaving) return;
      const bounds = presetBounds(this._editingPreset, this._ptemp);
      const stepped = Math.round((this._presetEditValue + delta) * 2) / 2;
      this._presetEditValue = Math.min(bounds.max, Math.max(bounds.min, stepped));
      this._patchPresetStepper();
    }
    async _savePreset() {
      if (this._editingPreset === null || this._presetSaving) return;
      const code = this._editingPreset;
      const ptemp = this._ptemp ? this._ptemp.slice() : [null, null, null];
      ptemp[code] = this._presetEditValue;
      if (ptemp.some((value) => value === null || value === void 0)) {
        this._presetError = "No current preset values yet; try again once the heater has reported.";
        this._patchPresetStepper();
        return;
      }
      this._presetSaving = true;
      this._presetError = null;
      this._patchPresetStepper();
      try {
        await this._hass.callService("termoweb_local", "set_preset_temperatures", {
          entity_id: this._config.entity,
          cold: ptemp[0],
          night: ptemp[1],
          day: ptemp[2]
        });
        const state = this._hass.states[this._config.entity];
        this._ptemp = state && Array.isArray(state.attributes.ptemp) ? state.attributes.ptemp.slice() : ptemp;
        this._editingPreset = null;
        this._presetEditValue = null;
      } catch (err) {
        this._presetError = err && (err.message || err.body && err.body.message) || "set_preset_temperatures call failed";
        this._editingPreset = null;
        this._presetEditValue = null;
      } finally {
        this._presetSaving = false;
        this._patchLegend();
        this._patchPresetStepper();
      }
    }
    _patchPresetStepper() {
      if (!this._presetEls) return;
      PRESETS.forEach((preset) => {
        const els = this._presetEls[preset.code];
        if (!els) return;
        const editing = this._editingPreset === preset.code;
        els.swatch.classList.toggle("editing", editing);
        els.view.hidden = editing;
        els.stepper.hidden = !editing;
        if (!editing) return;
        const bounds = presetBounds(preset.code, this._ptemp);
        els.valueEl.textContent = formatTemp(this._presetEditValue) || "--";
        els.minusBtn.disabled = this._presetSaving || this._presetEditValue <= bounds.min;
        els.plusBtn.disabled = this._presetSaving || this._presetEditValue >= bounds.max;
        els.confirmBtn.disabled = this._presetSaving;
        els.cancelBtn.disabled = this._presetSaving;
      });
      if (this._presetErrorEl) {
        this._presetErrorEl.hidden = !this._presetError;
        if (this._presetError) this._presetErrorEl.textContent = this._presetError;
      }
    }
    // Called for every `hass` push once the grid structure already exists
    // and its column count hasn't changed. Per spec: while the user has
    // unsaved edits, nothing in the DOM may change except the stale note --
    // the grid values shown are the user's own, not the (possibly newer)
    // live ones.
    _patchInPlace() {
      this._patchStaleNote();
      if (this._dirty) return;
      const hoursPerSlot = hoursPerSlotFor(this._renderedSlotsPerDay);
      this._syncCellsFromGrid(hoursPerSlot);
      this._patchLegend();
      this._updateActionsState();
      this._updateDirtyDot();
    }
    _legendLabelText(preset) {
      const temp = this._ptemp ? formatTemp(this._ptemp[preset.code]) : null;
      return temp ? `${preset.label} (${temp})` : preset.label;
    }
    _patchLegend() {
      if (arraysEqual(this._ptemp, this._legendPtemp)) return;
      this._legendPtemp = this._ptemp ? this._ptemp.slice() : null;
      PRESETS.forEach((preset) => {
        const label = this._legendLabelEls && this._legendLabelEls[preset.code];
        if (label) label.textContent = this._legendLabelText(preset);
      });
    }
    _patchStaleNote() {
      if (!this._staleNoteEl) return;
      this._staleNoteEl.hidden = !this._staleNote;
      if (this._staleNote) this._staleNoteEl.textContent = STALE_NOTE_TEXT;
    }
    _patchError() {
      if (!this._errorEl) return;
      this._errorEl.hidden = !this._error;
      if (this._error) this._errorEl.textContent = this._error;
    }
    _applyCellVisual(cell, value, hoursPerSlot) {
      const preset = PRESET_BY_CODE.get(value);
      cell.className = preset ? "cell" : "cell unset";
      cell.style.backgroundColor = preset ? preset.color : UNSET_COLOR;
      const day = Number(cell.dataset.day);
      const slot = Number(cell.dataset.slot);
      const timeLabel = formatHourLabel(slot * hoursPerSlot);
      const presetLabel = preset ? preset.label : "Unset";
      cell.setAttribute("aria-label", `${DAY_LABELS[day]} ${timeLabel}, ${presetLabel}`);
    }
    // Diffs this._grid against the last-painted snapshot and patches only the
    // cells that actually changed -- used both for hass-driven syncs (once
    // not dirty) and for local bulk edits (copy-to-all-days, revert).
    _syncCellsFromGrid(hoursPerSlot) {
      if (!this._gridEl || !this._domGrid) return;
      for (let idx = 0; idx < this._grid.length; idx++) {
        const value = this._grid[idx];
        if (this._domGrid[idx] !== value) {
          this._domGrid[idx] = value;
          this._paintCellDom(idx, value, hoursPerSlot);
        }
      }
    }
    _paintCellDom(idx, value, hoursPerSlot) {
      const cell = this._gridEl && this._gridEl.querySelector(`.cell[data-idx="${idx}"]`);
      if (cell) this._applyCellVisual(cell, value, hoursPerSlot);
    }
    _setCellValue(idx, value, hoursPerSlot) {
      if (this._grid[idx] === value) return;
      this._grid[idx] = value;
      this._domGrid[idx] = value;
      this._dirty = true;
      this._paintCellDom(idx, value, hoursPerSlot);
      this._updateActionsState();
      this._updateDirtyDot();
    }
    _cycleCell(idx, hoursPerSlot) {
      const next = nextPresetValue(this._grid[idx]);
      this._setCellValue(idx, next, hoursPerSlot);
      return next;
    }
    _onCellPointerDown(ev, hoursPerSlot) {
      const cell = ev.target.closest(".cell");
      if (!cell) return;
      ev.preventDefault();
      const idx = Number(cell.dataset.idx);
      this._painting = true;
      this._lastPaintedIdx = idx;
      this._paintValue = this._cycleCell(idx, hoursPerSlot);
    }
    _onCellPointerMove(ev, hoursPerSlot) {
      if (!this._painting) return;
      const cell = ev.target.closest(".cell");
      if (!cell) return;
      const idx = Number(cell.dataset.idx);
      if (idx === this._lastPaintedIdx) return;
      this._lastPaintedIdx = idx;
      this._setCellValue(idx, this._paintValue, hoursPerSlot);
    }
    _stopPainting() {
      this._painting = false;
      this._paintValue = null;
      this._lastPaintedIdx = null;
    }
    _onCellKeyDown(ev, hoursPerSlot) {
      if (ev.key === "Escape") {
        this._cancelCopyMode();
        return;
      }
      if (ev.key !== "Enter" && ev.key !== " " && ev.key !== "Spacebar") return;
      const cell = ev.target.closest(".cell");
      if (!cell) return;
      ev.preventDefault();
      this._cycleCell(Number(cell.dataset.idx), hoursPerSlot);
    }
    _updateActionsState() {
      const hasUnset = this._grid.some((v) => v === null || v === void 0);
      if (this._saveBtnEl) this._saveBtnEl.disabled = this._saving || hasUnset || !this._dirty;
      if (this._revertBtnEl) this._revertBtnEl.disabled = this._saving || !this._dirty;
    }
    _updateSaveButtonLabel() {
      if (this._saveBtnEl) this._saveBtnEl.textContent = this._saving ? "Saving..." : "Save";
    }
    _updateDirtyDot() {
      if (!this._titleEl) return;
      const existing = this._titleEl.querySelector(".dirty-dot");
      if (this._dirty && !existing) {
        const dot = document.createElement("span");
        dot.className = "dirty-dot";
        dot.title = "Unsaved changes";
        this._titleEl.appendChild(dot);
      } else if (!this._dirty && existing) {
        existing.remove();
      }
    }
    // Copy mode: clicking "Copy to" on a row turns that row's button into
    // confirm/cancel and every other row's button into a checkbox. Only one
    // row's controls track state (this._copySourceDay / this._copyTargets);
    // _patchCopyMode() is the only thing that reads it into the DOM, so a
    // hass-driven _patchInPlace() (which never calls it) can't disturb an
    // in-progress copy.
    _startCopyMode(day) {
      this._copySourceDay = day;
      this._copyTargets = /* @__PURE__ */ new Set();
      this._patchCopyMode();
    }
    _cancelCopyMode() {
      if (this._copySourceDay === null) return;
      this._copySourceDay = null;
      this._copyTargets = /* @__PURE__ */ new Set();
      this._patchCopyMode();
    }
    _toggleCopyTarget(day, checked) {
      if (this._copySourceDay === null) return;
      if (checked) this._copyTargets.add(day);
      else this._copyTargets.delete(day);
    }
    _confirmCopy(slotsPerDay) {
      if (this._copySourceDay === null) return;
      if (this._copyTargets.size) {
        this._grid = copyDayToDays(this._grid, this._copySourceDay, this._copyTargets, slotsPerDay);
        this._dirty = true;
        this._syncCellsFromGrid(hoursPerSlotFor(slotsPerDay));
        this._updateActionsState();
        this._updateDirtyDot();
      }
      this._cancelCopyMode();
    }
    _patchCopyMode() {
      if (!this._rowEls) return;
      const active = this._copySourceDay !== null;
      for (let day = 0; day < DAYS_PER_WEEK; day++) {
        const els = this._rowEls[day];
        if (!els) continue;
        const isSource = active && this._copySourceDay === day;
        els.copyBtn.hidden = active;
        els.confirmBtn.hidden = !isSource;
        els.cancelBtn.hidden = !isSource;
        els.checkbox.hidden = !active || isSource;
        if (!active) els.checkbox.checked = false;
      }
    }
    async _save() {
      if (this._saving) return;
      this._saving = true;
      this._error = null;
      this._updateActionsState();
      this._updateSaveButtonLabel();
      this._patchError();
      try {
        await this._hass.callService("termoweb_local", "set_schedule", {
          entity_id: this._config.entity,
          prog: this._grid.slice()
        });
        this._baselineProg = this._grid.slice();
        this._dirty = false;
        this._staleNote = false;
      } catch (err) {
        this._error = err && (err.message || err.body && err.body.message) || "set_schedule call failed";
      } finally {
        this._saving = false;
        this._updateActionsState();
        this._updateSaveButtonLabel();
        this._updateDirtyDot();
        this._patchStaleNote();
        this._patchError();
      }
    }
  };
  if (!customElements.get("termoweb-local-schedule-card")) {
    customElements.define("termoweb-local-schedule-card", TermowebLocalScheduleCard);
  }
  window.customCards = window.customCards || [];
  window.customCards.push({
    type: "termoweb-local-schedule-card",
    name: "Termoweb Local schedule card",
    description: "Weekly heater schedule editor for the termoweb_local integration.",
    preview: true
  });
})();
